package main

import (
	"github.com/newrelic/infra-integrations-sdk/data/metric"
)

// TODO delete unnecessary fields

type metricDefinition struct {
	MetricName string
	SourceType metric.SourceType
}

// HAProxyListenerStats holds the metric definitions for a listener
var HAProxyListenerStats = map[string]metricDefinition{
	"pxname": {MetricName: "listener.proxyName", SourceType: metric.ATTRIBUTE},
	"svname": {MetricName: "listener.serviceName", SourceType: metric.ATTRIBUTE},
	"scur":   {MetricName: "listener.currentSessions", SourceType: metric.GAUGE},
	"smax":   {MetricName: "listener.maxSessions", SourceType: metric.GAUGE},
	"stot":   {MetricName: "listener.sessionsPerSecond", SourceType: metric.RATE},
	"bin":    {MetricName: "listener.bytesInPerSecond", SourceType: metric.RATE},
	"bout":   {MetricName: "listener.bytesOutPerSecond", SourceType: metric.RATE},
	"dreq":   {MetricName: "listener.requestsDenied.securityConcernsPerSecond", SourceType: metric.RATE},
	"dresp":  {MetricName: "listener.responsesDenied.securityConcernsPerSecond", SourceType: metric.RATE},
	"ereq":   {MetricName: "listener.requestErrorsPerSecond", SourceType: metric.RATE},
	"status": {MetricName: "listener.status", SourceType: metric.ATTRIBUTE},
	"type":   {MetricName: "listener.type", SourceType: metric.GAUGE},
	"mode":   {MetricName: "listener.mode", SourceType: metric.ATTRIBUTE},
	"dcon":   {MetricName: "listener.requestsDenied.tcpRequestConnectionRulesPerSecond", SourceType: metric.RATE},
	"dses":   {MetricName: "listener.requestsDenied.tcpRequestSessionRulesPerSecond", SourceType: metric.RATE},
}

// HAProxyFrontendStats holds the metric definitions for a frontend
var HAProxyFrontendStats = map[string]metricDefinition{
	"pxname":        {MetricName: "frontend.proxyName", SourceType: metric.ATTRIBUTE},
	"svname":        {MetricName: "frontend.serviceName", SourceType: metric.ATTRIBUTE},
	"scur":          {MetricName: "frontend.currentSessions", SourceType: metric.GAUGE},
	"smax":          {MetricName: "frontend.maxSessions", SourceType: metric.GAUGE},
	"stot":          {MetricName: "frontend.sessionsPerSecond", SourceType: metric.RATE},
	"bin":           {MetricName: "frontend.bytesInPerSecond", SourceType: metric.RATE},
	"bout":          {MetricName: "frontend.bytesOutPerSecond", SourceType: metric.RATE},
	"dreq":          {MetricName: "frontend.requestsDenied.securityConcernsPerSecond", SourceType: metric.RATE},
	"dresp":         {MetricName: "frontend.responsesDenied.securityConcernsPerSecond", SourceType: metric.RATE},
	"ereq":          {MetricName: "frontend.requestErrorsPerSecond", SourceType: metric.RATE},
	"status":        {MetricName: "frontend.status", SourceType: metric.ATTRIBUTE},
	"type":          {MetricName: "frontend.type", SourceType: metric.GAUGE},
	"rate_max":      {MetricName: "frontend.maxSessionsPerSecond", SourceType: metric.GAUGE},
	"hrsp_1xx":      {MetricName: "frontend.http100ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_2xx":      {MetricName: "frontend.http200ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_3xx":      {MetricName: "frontend.http300ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_4xx":      {MetricName: "frontend.http400ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_5xx":      {MetricName: "frontend.http500ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_other":    {MetricName: "frontend.httpOtherResponsesPerSecond", SourceType: metric.RATE},
	"req_rate_max":  {MetricName: "frontend.httpRequests.maxPerSecond", SourceType: metric.RATE},
	"req_tot":       {MetricName: "frontend.httpRequestsPerSecond", SourceType: metric.RATE},
	"mode":          {MetricName: "frontend.mode", SourceType: metric.ATTRIBUTE},
	"conn_rate_max": {MetricName: "frontend.maxConnectionsPerSecond", SourceType: metric.GAUGE},
	"conn_tot":      {MetricName: "frontend.connectionsPerSecond", SourceType: metric.RATE},
	"intercepted":   {MetricName: "frontend.interceptedRequestsPerSecond", SourceType: metric.RATE},
	"dcon":          {MetricName: "frontend.requestsDenied.tcpRequestConnectionRulesPerSecond", SourceType: metric.RATE},
	"dses":          {MetricName: "frontend.requestsDenied.tcpRequestSessionRulesPerSecond", SourceType: metric.RATE},
}

// HAProxyBackendStats holds the metric definitions for a backend
var HAProxyBackendStats = map[string]metricDefinition{
	"pxname":      {MetricName: "backend.proxyName", SourceType: metric.ATTRIBUTE},
	"qcur":        {MetricName: "backend.currentQueuedRequestsWithoutServer", SourceType: metric.GAUGE},
	"qmax":        {MetricName: "backend.maxQueuedRequestsWithoutServer", SourceType: metric.GAUGE},
	"scur":        {MetricName: "backend.currentSessions", SourceType: metric.GAUGE},
	"smax":        {MetricName: "backend.maxSessions", SourceType: metric.GAUGE},
	"stot":        {MetricName: "backend.sessionsPerSecond", SourceType: metric.RATE},
	"bin":         {MetricName: "backend.bytesInPerSecond", SourceType: metric.RATE},
	"bout":        {MetricName: "backend.bytesOutPerSecond", SourceType: metric.RATE},
	"dreq":        {MetricName: "backend.requestsDenied.securityConcernsPerSecond", SourceType: metric.RATE},
	"dresp":       {MetricName: "backend.responsesDenied.securityConcernsPerSecond", SourceType: metric.RATE},
	"econ":        {MetricName: "backend.connectingRequestErrorsPerSecond", SourceType: metric.RATE},
	"eresp":       {MetricName: "backend.responseErrorsPerSecond", SourceType: metric.RATE},
	"wretr":       {MetricName: "backend.connectionRetriesPerSecond", SourceType: metric.RATE},
	"wredis":      {MetricName: "backend.requestRedispatchPerSecond", SourceType: metric.RATE},
	"status":      {MetricName: "backend.status", SourceType: metric.ATTRIBUTE},
	"weight":      {MetricName: "backend.totalWeight", SourceType: metric.GAUGE},
	"act":         {MetricName: "backend.activeServers", SourceType: metric.GAUGE},
	"bck":         {MetricName: "backend.backupServers", SourceType: metric.GAUGE},
	"chkdown":     {MetricName: "backend.upToDownTransitionsPerSecond", SourceType: metric.RATE},
	"lastchg":     {MetricName: "backend.timeSinceLastUpDownTransitionInSeconds", SourceType: metric.RATE},
	"downtime":    {MetricName: "backend.downtimeInSeconds", SourceType: metric.GAUGE},
	"lbtot":       {MetricName: "backend.serverSelectedPerSecond", SourceType: metric.RATE},
	"type":        {MetricName: "backend.type", SourceType: metric.GAUGE},
	"rate_max":    {MetricName: "backend.maxSessionsPerSecond", SourceType: metric.GAUGE},
	"hrsp_1xx":    {MetricName: "backend.http100ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_2xx":    {MetricName: "backend.http200ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_3xx":    {MetricName: "backend.http300ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_4xx":    {MetricName: "backend.http400ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_5xx":    {MetricName: "backend.http500ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_other":  {MetricName: "backend.httpOtherResponsesPerSecond", SourceType: metric.RATE},
	"req_tot":     {MetricName: "backend.httpRequestsPerSecond", SourceType: metric.RATE},
	"cli_abrt":    {MetricName: "backend.dataTransfersAbortedByClientPerSecond", SourceType: metric.RATE},
	"srv_abrt":    {MetricName: "backend.dataTransfersAbortedByServerPerSecond", SourceType: metric.RATE},
	"comp_in":     {MetricName: "backend.httpResponseBytesFedToCompressorPerSecond", SourceType: metric.RATE},
	"comp_out":    {MetricName: "backend.httpResponseBytesEmittedByCompressorPerSecond", SourceType: metric.RATE},
	"comp_byp":    {MetricName: "backend.bytesThatBypassedCompressorPerSecond", SourceType: metric.RATE},
	"comp_rsp":    {MetricName: "backend.httpResponsesCompressedPerSecond", SourceType: metric.RATE},
	"lastsess":    {MetricName: "backend.timeSinceLastSessionAssignedInSeconds", SourceType: metric.RATE},
	"qtime":       {MetricName: "backend.averageQueueTimeInSeconds", SourceType: metric.RATE},
	"ctime":       {MetricName: "backend.averageConnectTimeInSeconds", SourceType: metric.RATE},
	"rtime":       {MetricName: "backend.averageResponseTimeInSeconds", SourceType: metric.RATE},
	"ttime":       {MetricName: "backend.averageTotalSessionTimeInSeconds", SourceType: metric.RATE},
	"cookie":      {MetricName: "backend.cookieName", SourceType: metric.ATTRIBUTE},
	"mode":        {MetricName: "backend.mode", SourceType: metric.ATTRIBUTE},
	"intercepted": {MetricName: "backend.interceptedRequestsPerSecond", SourceType: metric.RATE},
}

// HAProxyServerStats holds the metric definitions for a server
var HAProxyServerStats = map[string]metricDefinition{
	"pxname":         {MetricName: "server.proxyName", SourceType: metric.ATTRIBUTE},
	"svname":         {MetricName: "server.serviceName", SourceType: metric.ATTRIBUTE},
	"qcur":           {MetricName: "server.currentQueuedRequestsWithoutServer", SourceType: metric.GAUGE},
	"qmax":           {MetricName: "server.maxQueuedRequestsWithoutServer", SourceType: metric.GAUGE},
	"scur":           {MetricName: "server.currentSessions", SourceType: metric.GAUGE},
	"smax":           {MetricName: "server.maxSessions", SourceType: metric.GAUGE},
	"stot":           {MetricName: "server.sessionsPerSecond", SourceType: metric.RATE},
	"bin":            {MetricName: "server.bytesInPerSecond", SourceType: metric.RATE},
	"bout":           {MetricName: "server.bytesOutPerSecond", SourceType: metric.RATE},
	"dreq":           {MetricName: "server.requestsDenied.securityConcernsPerSecond", SourceType: metric.RATE},
	"dresp":          {MetricName: "server.responsesDenied.securityConcernsPerSecond", SourceType: metric.RATE},
	"econ":           {MetricName: "server.connectingRequestErrorsPerSecond", SourceType: metric.RATE},
	"eresp":          {MetricName: "server.responseErrorsPerSecond", SourceType: metric.RATE},
	"wretr":          {MetricName: "server.connectionRetriesPerSecond", SourceType: metric.RATE},
	"wredis":         {MetricName: "server.requestRedispatchPerSecond", SourceType: metric.RATE},
	"status":         {MetricName: "server.status", SourceType: metric.ATTRIBUTE},
	"weight":         {MetricName: "server.serverWeight", SourceType: metric.GAUGE},
	"act":            {MetricName: "server.isActive", SourceType: metric.GAUGE},
	"bck":            {MetricName: "server.isBackup", SourceType: metric.GAUGE},
	"chkfail":        {MetricName: "server.failedChecksPerSecond", SourceType: metric.RATE},
	"chkdown":        {MetricName: "server.upToDownTransitionsPerSecond", SourceType: metric.RATE},
	"lastchg":        {MetricName: "server.timeSinceLastUpDownTransitionInSeconds", SourceType: metric.RATE},
	"downtime":       {MetricName: "server.downtimeInSeconds", SourceType: metric.GAUGE},
	"sid":            {MetricName: "server.serverID", SourceType: metric.ATTRIBUTE},
	"throttle":       {MetricName: "server.throttlePercentage", SourceType: metric.GAUGE},
	"lbtot":          {MetricName: "server.serverSelectedPerSecond", SourceType: metric.RATE},
	"type":           {MetricName: "server.type", SourceType: metric.GAUGE},
	"rate_max":       {MetricName: "server.maxSessionsPerSecond", SourceType: metric.GAUGE},
	"check_status":   {MetricName: "server.healthCheckStatus", SourceType: metric.ATTRIBUTE},
	"check_code":     {MetricName: "server.layerCode", SourceType: metric.ATTRIBUTE},
	"check_duration": {MetricName: "server.healthCheckDurationInMilliseconds", SourceType: metric.GAUGE},
	"hrsp_1xx":       {MetricName: "server.http100ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_2xx":       {MetricName: "server.http200ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_3xx":       {MetricName: "server.http300ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_4xx":       {MetricName: "server.http400ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_5xx":       {MetricName: "server.http500ResponsesPerSecond", SourceType: metric.RATE},
	"hrsp_other":     {MetricName: "server.httpOtherResponsesPerSecond", SourceType: metric.RATE},
	"hanafail":       {MetricName: "server.failedHealthCheckDetails", SourceType: metric.ATTRIBUTE},
	"cli_abrt":       {MetricName: "server.dataTransfersAbortedByClientPerSecond", SourceType: metric.RATE},
	"srv_abrt":       {MetricName: "server.dataTransfersAbortedByServerPerSecond", SourceType: metric.RATE},
	"lastsess":       {MetricName: "server.timeSinceLastSessionAssignedInSeconds", SourceType: metric.RATE},
	"last_chk":       {MetricName: "server.healthCheckContents", SourceType: metric.ATTRIBUTE},
	"last_agt":       {MetricName: "server.agentCheckContents", SourceType: metric.ATTRIBUTE},
	"qtime":          {MetricName: "server.averageQueueTimeInSeconds", SourceType: metric.RATE},
	"ctime":          {MetricName: "server.averageConnectTimeInSeconds", SourceType: metric.RATE},
	"rtime":          {MetricName: "server.averageResponseTimeInSeconds", SourceType: metric.RATE},
	"ttime":          {MetricName: "server.averageTotalSessionTimeInSeconds", SourceType: metric.RATE},
	"agent_status":   {MetricName: "server.agentStatus", SourceType: metric.ATTRIBUTE},
	"agent_duration": {MetricName: "server.agentDurationSeconds", SourceType: metric.GAUGE},
	"check_desc":     {MetricName: "server.checkStatusDescription", SourceType: metric.ATTRIBUTE},
	"agent_desc":     {MetricName: "server.agentStatusDescription", SourceType: metric.ATTRIBUTE},
	"cookie":         {MetricName: "server.cookieValue", SourceType: metric.ATTRIBUTE},
	"mode":           {MetricName: "server.mode", SourceType: metric.ATTRIBUTE},
}

// HAProxyInventory holds the list of inventory items to be collected from the stats request
var HAProxyInventory = map[string]struct{}{
	"slim":     {},
	"pid":      {},
	"sid":      {},
	"iid":      {},
	"rate_lim": {},
	"qmax":     {},
}
