name: Push/PR

on:
  push:
    branches:
      - main
      - master
      - renovate/**
  pull_request:
  workflow_dispatch:

jobs:
  push-pr:
    uses: newrelic/coreint-automation/.github/workflows/reusable_push_pr.yaml@v2
    secrets: inherit
    with:
      integration: "haproxy"
      run_test_build_fake_prerelease: true
