name: Release pipeline

on:
  release:
    types:
      - released
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INTEGRATION: "haproxy"
  ORIGINAL_REPO_NAME: 'newrelic/nri-haproxy'
  TAG: ${{ github.event.release.tag_name }}

jobs:

  publish-to-s3:
    name: Send release assets to S3
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}
      - name: Publish to S3 action
        uses: newrelic/infrastructure-publish-action@main
        env:
          AWS_S3_BUCKET_NAME: "nr-downloads-main"
          AWS_S3_LOCK_BUCKET_NAME: "onhost-ci-lock"
          AWS_REGION: "us-east-1"
          DISABLE_LOCK: false
          SCHEMA: "ohi"
          ENV: release
        with:
          # lock enabled
          disable_lock: ${{ env.DISABLE_LOCK }}
          run_id: ${{ github.run_id }}
          env: ${{ env.ENV }}
          tag: ${{env.TAG}}
          app_name: "nri-${{env.INTEGRATION}}"
          repo_name: ${{ env.ORIGINAL_REPO_NAME }}
          # 'ohi' is for integrations
          schema: ${{env.SCHEMA}}
          aws_region: ${{ env.AWS_REGION }}
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN_PROD }}
          aws_role_session_name: ${{ secrets.AWS_ROLE_SESSION_NAME_PROD }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws_s3_bucket_name: ${{ env.AWS_S3_BUCKET_NAME }}
          # used for locking in case of concurrent releases
          aws_s3_lock_bucket_name: ${{ env.AWS_S3_LOCK_BUCKET_NAME }}
          # used for signing package stuff
          gpg_passphrase: ${{ secrets.OHAI_GPG_PASSPHRASE }}
          gpg_private_key_base64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }}
